### PR TITLE
Wrote ReadME.md and created LICENSE

### PR DESCRIPTION
**Pull request by ZiClaud**

### CODE REVIEW

**Comment by ZiClaud** [comment]
Inside the "Community" links, should I add the facebook and twitter ones? (They appear in the menu of the app)

**Review by himanshunaidu — APPROVED** [review]

**Comment by thuiop** [comment]
> Inside the "Community" links, should I add the facebook and twitter ones? (They appear in the menu of the app)

I don't know, are they active?

**Comment by ZiClaud** [comment]
Not anymore, they were updated by the author 
I can link them and write (inactive) next to them

**Comment by thuiop** [comment]
If they are not used, it is fine that way I think.

**Pull request merged**
