### PR TITLE
Issues #41 - Stats for mobile now looks good

### PR DESCRIPTION
**Pull request by ZiClaud**
Needs testing, should work even for when we reach book 3 chapter 11, but I haven't tested it.

### CODE REVIEW

**Comment by himanshunaidu** [comment]
I'd say this is better now that we don't have to hard-code the row and column numbers on each field.
Just one question tho: Is this how it looks in mobile view? If so, 
Stats Mobile
I wonder, if it is mobile view that we are trying to improve, maybe reducing the font size would be good? Just an optional suggestion.

**Comment by ZiClaud** [comment]
I can change it to this for mobile if you guys prefer (looks more like the original app).
Personally, I wouldn't change the font size, I would rather keep it pretty much the same everywhere

Screenshot from 2024-09-14 10-49-22

**Comment by himanshunaidu** [comment]
Cool. Yeah I don't think either option is a big deal for now. 
This is fine by me.

**Review by himanshunaidu — APPROVED** [review]

**Comment by ZiClaud** [comment]
Updated, you can merge now

**Pull request merged**
