### PR TITLE
Pagination in the Saves page

### PR DESCRIPTION
**Pull request by himanshunaidu**
Currently, one can have 50 saves with this pagination.
I believe it's fine to have this as the first version of the pagination. 

Saves with Pagination

### CODE REVIEW

**Comment by himanshunaidu** [comment]
This is the first iteration of pagination that tries to work within the constraints of the saves ejs template.
There are only minor changes to the saves ejs template, and changes to the default path to access the saves page. 
Please do let me know if there are some unintended consequences to the default path changes.

**Comment by himanshunaidu** [comment]
This pagination feature can be improved at the cost of more rework of the saves page. Here is a backend heavy approach that could be seen as an improvement in some ways:
- Make the saves.ejs template render all the saves that are provided by the backend instead of filtering out the specific saves itself by using the key.
- Make the backend filter out all the saves depending on the page that has been requested

Advantages:
- Less hard-coding in the frontend.
- More control of pagination logic on the backend (instead of the control being slightly distributed between the frontend and backend)

Disadvantages
- While backend does get control of the pagination, frontend still is the one that decides how to name the saves, which means that the backend is still going to have to abide by the naming rules of the frontend. 

Mostly, I will prefer not to implement this right now, and make do with the current implementation (as long as the current implementation does not have any major issues or bugs). It is better to focus on the exports feature instead.

**Comment by thuiop** [comment]
Looks fine with me for a first iteration. It does seem a bit clunky though; there is probably a better/more flexible way to achieve that. But I will merge this for now.

**Comment by himanshunaidu** [comment]
Yes I agree. 
If time permits, I will look into that once the Export/Import feature is done. 
But unfortunately, I have many extra commitments starting in the coming weeks, so I'd at least like to have the first iterations out of the way, as these features, while good to have, are not the most critical.

**Pull request merged**
